### ISSUE TITLE
'nunjucks-tag-spaceless' is not in the npm registry

### ISSUE THREAD

**Issue by stefan-b314** [jbmoelker/nunjucks-tag-spaceless#1]
Hi,

I just wanted to install your extension via npm, but it seems that it has not yet been published to npm, as the `npm install` fails:

```
Registry returned 404 for GET on https://registry.npmjs.org/nunjucks-tag-spaceless
'nunjucks-tag-spaceless' is not in the npm registry.
```

Can you publish it to npm, please!?
Thanks in advance!

Stefan

**Comment by jbmoelker** [comment]
@stefanullinger oops. So sorry. Just [published it to npm](https://www.npmjs.com/package/nunjucks-tag-spaceless).
